class UrlTypes:
    YT_URL = "YT_URL"
    SPOTIFY_URL = "SPOTIFY_URL"
    YT_PLAYLIST = "YT_PLAYLIST"
    SPOTIFY_PLAYLIST = "SPOTIFY_PLAYLIST"
    SPOTIFY_ALBUM = "SPOTIFY_ALBUM"
    SPOTIFY_ARTIST = "SPOTIFY_ARTIST"
    UNKNOWN = "UNKNOWN"
